# Use the official Tomcat base image
FROM tomcat:9.0

# Install Java 17 if required (update to the latest version as per your project needs)
RUN apt-get update && apt-get install -y openjdk-17-jdk

# Set JAVA_HOME environment variable
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

# Expose port 8080
EXPOSE 8080

# Copy the WAR file to the webapps directory in Tomcat
COPY target/StudentDetails.war /usr/local/tomcat/webapps/ROOT.war
